# -*- coding: utf-8 -*-
"""GTN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXUQVdNl__wGvOooOGlAYCoGeZZO-Fw5
"""

pip install colorama

import time
import random
from IPython.display import clear_output
from colorama import init, Fore, Back, Style


def objectives(remain):
  print(Fore.YELLOW + "Objective: " + Fore.RESET + "Guess the number between 1 - 100")
  if remain == 1:
    print("You have " + Fore.RED + f"{remain} attempt" + Fore.RESET + " to guess the correct number")
  else:
    print("You have " + Fore.GREEN + f"{remain} attempts" + Fore.RESET + " to guess the correct number")

def hint(hidden, remain):
  if remain == 3:
    if hidden % 2 == 0:
      print(Fore.YELLOW + "Hint:" + Fore.RESET + " The number is even")
    else:
      print(Fore.YELLOW + "Hint: " + Fore.RESET + " The number is odd")
  elif remain == 2:
    lowerrange = (hidden // 10) * 10
    upperrange = lowerrange + 10
    print(Fore.YELLOW + "Hint: " + Fore.RESET + f"The number is near {lowerrange} - {upperrange}")

def game():
  max_attempts = 5
  user_attempts = 0
  hidden = random.randint(1, 100)

  while user_attempts < max_attempts:
    remaining = max_attempts - user_attempts
    objectives(remaining)

    if remaining == 3:
        hint(hidden, remaining)
    elif remaining == 2:
        hint(hidden, remaining)

    guess = (input(""))
    try:
      user_guess = int(guess)
      time.sleep(2)
    except ValueError:
      clear_output()
      print(Fore.RED + "Invalid! Enter a number")
      time.sleep(2)
      clear_output()
      continue
    if user_guess < 1 or user_guess > 100:
      clear_output()
      print(Fore.RED + "Invalid! Enter a number between 1 - 100")
      time.sleep(2)
      clear_output()
      continue

    user_attempts += 1

    if user_guess == hidden:
      print(Fore.GREEN + f"Correct!!! The number was {hidden}." + Fore.RESET + "You got it in {user_attempts} attempts")
      break

    elif user_guess > hidden:
      clear_output()
      print(Fore.RED + "Too High, Maybe a lower number" + Fore.RESET)
      time.sleep(2)
      clear_output()

    elif user_guess < hidden:
      clear_output()
      print(Fore.RED + "Too Low, Maybe a higher number" + Fore.RESET)
      time.sleep(2)
      clear_output()

  if user_guess != hidden and user_attempts == max_attempts:
    clear_output()
    print(Fore.RED + "Unfortunately you are out of attempts" + Fore.RESET + f", The number was " + Fore.YELLOW + f"{hidden}")
    time.sleep(2)
    clear_output()
    again = input("Play again? [Y/N] ").capitalize()
    if again == "Y":
      time.sleep(2)
      clear_output()
      game()
    else:
      clear_output()
      print(Fore.YELLOW + "Thanks for playing!" + Fore.RESET)

def main():
  print(Fore.YELLOW + "Guess The Number!" + Fore.RESET)
  print("Made by Emman Diamond")
  select = input("Start [Y/N]? ").capitalize()
  if select == "Y":
    time.sleep(2)
    clear_output()
    game()
  else:
    clear_output()
    print(Fore.YELLOW + "Thanks for playing!" + Fore.RESET)

if __name__ == "__main__":
    main()